baseURL: "https://dsba5122-spring2019.netlify.com"
languageCode: en-us
title: Visual Analytics
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 8
    - name: Canvas
      url: "https://uncc.instructure.com/courses/100065"
      weight: 4
    - name: RStudio.cloud
      url: "https://rstudio.cloud/spaces/7976/"
      weight: 5
    - name: Class Slack
      url: "https://unccdsba5122s2019.slack.com"
      weight: 6
    - name: DataCamp
      url: "https://www.datacamp.com/groups/dsba5122-visual-analytics-58036aae-d5c5-424e-aa2a-eab645c8a12a"
      weight: 7
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Ryan Wesslen
  thumbnail: /images/dsba5122.png
  instructor: 
    name: Ryan Wesslen
    email: rwesslen@uncc.edu
    url: "https://wesslen.netlify.com"
    twitter: ryanwesslen
    github: wesslen
    office: CenterCity
  course:
    number: DSBA 5122
    semester: Spring 2019
    days: "Mondays"
    time: "6:00–8:45 PM"
    location: "Room 110M: Packard Place"
    twitter: ryanwesslen
    dates: "January 14 – May 6, 2019"
    github: "wesslen/dsba5122-spring2019"
    slack: "https://unccdsba5122s2019.slack.com"
    copyrightYear: "2019"
    contactDetails: >-
      [Office Hours via Calendly](https://calendly.com/rwesslen/15min/)
  university: 
    name: University of North Carolina at Charlotte
    url: "https://www.uncc.edu"
  school:
    name: Data Science & Business Analytics Program
    url: "https://dsba.uncc.edu/"
  description: "Communicate science and statistics with beautiful graphics"
  primaryColor: "#046A38"
  secondaryColor: "#B9975B"
  credits: >-
    Original [website](https://datavizf18.classes.andrewheiss.com/) by [Andrew Heiss](https://www.andrewheiss.com/).
  logo:
    url: /images/dsba5122.png
    alt: Visual Analytics
  meta:
    twitterSite: "@ryanwesslen"
    twitterCreator: "@ryanwesslen"
